# Generated by Django 3.2.7 on 2021-10-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='progress_id',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='progress_id',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='process',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.gameprogress'),
        ),
    ]
