# Generated by Django 3.2.7 on 2021-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='description',
            field=models.TextField(blank=True, help_text='Url', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='mapped_to',
            field=models.TextField(blank=True, help_text='Enter vector of urls id', max_length=100, null=True),
        ),
    ]
