# Generated by Django 3.2.7 on 2021-10-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='process',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='progress_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.gameprogress'),
        ),
    ]
