# Generated by Django 3.2.7 on 2021-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211108_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprogress',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
