# Generated by Django 3.2.7 on 2021-11-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_gameprogress_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprogress',
            old_name='description',
            new_name='template',
        ),
    ]
